name: GitHub Classroom Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          server/package-lock.json
          client/package-lock.json
    
    - name: Install server dependencies
      run: cd server && npm ci
    
    - name: Install client dependencies
      run: cd client && npm ci
    
    - name: Run server tests
      run: cd server && npm test
      env:
        NODE_ENV: test
        JWT_SECRET: test-secret-key
        
    - name: Run client tests
      run: cd client && npm test -- --coverage --watchAll=false --passWithNoTests
      env:
        CI: true
        
    - name: Check test results
      run: |
        echo "Server tests completed"
        echo "Client tests completed"
    
    - name: Upload server coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./server/coverage
        flags: server-tests
        name: server-coverage
        fail_ci_if_error: false
        
    - name: Upload client coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./client/coverage
        flags: client-tests
        name: client-coverage
        fail_ci_if_error: false

  autograding:
    needs: test
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run autograding
      uses: education/autograding@v1